/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    CompletedTodoPanel: typeof import('./components/CompletedTodoPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TodoInput: typeof import('./components/TodoInput.vue')['default']
    TodoList: typeof import('./components/TodoList.vue')['default']
  }
}
